# Site settings
title: Luis Eduardo Brito
description: CTO & Co-Founder @ Devnup
email: hello@luiseduardobrito.me
baseurl: /
url: "http://luiseduardobrito.me" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username:
#twitter
twitter_username:
github_username:  luiseduardobrito

#linkedin
linkedin_username:

#google analytics
google_analytics_id :
#gplus
gplus_username:

#fb_username
fb_username: luiseduardo14

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name:
disqus_show_comment_count:

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  luis:
    display_name: Luís Eduardo Brito
    email: hello@luiseduardobrito.me
    fb: luiseduardo14
    linkedin:
    twitter:
    github: luiseduardobrito
