# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Luís Eduardo Brito
tagline:          'blog'
description:      'Tech blog and coding journal'
url:              https://luiseduardobrito.me
enforce_ssl:      luiseduardobrito.me

baseurl:
commentsystem:    google
disqus:           example

author:
  name:           Luís Eduardo Brito
  url:            https://luiseduardobrito.me

paginate:         5

# Custom vars
icon:             /assets/images/icon.jpg
cover:            /assets/images/blue.png

social:
#  - icon:         twitter
#    url:          https://twitter.com/iancamporez
#    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/luiseduardobrito
    desc:         Fork me on github

#  - icon:         googleplus-alt
#    url:          https://google.com/+IanCamporezBrunelli
#    desc:         Add me on google+

  - icon:         feed
    url:          https://luiseduardobrito.me/atom.xml
    desc:         RSS

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Luis Eduardo Brito
  url:            https://luiseduardobrito.me
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-47639609-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
